# Generated by Django 6.1 on 2026-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="imagens/%Y/%m/%d/"),
        ),
    ]
