# Generated by Django 6.1 on 2026-08-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0002_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="ativa",
            field=models.BooleanField(default=True),
        ),
    ]
