# Generated by Django 6.1 on 2026-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0003_categoria_ativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
