# Generated by Django 6.1 on 2026-08-18 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0004_produto_disponivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.CheckConstraint(
                condition=models.Q(("preco__gte", 0)), name="preco_nao_negativo"
            ),
        ),
    ]
