# Generated by Django 6.1 on 2026-08-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0005_alter_produto_preco_produto_preco_nao_negativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("telefone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
