# Generated by Django 6.1 on 2026-08-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0006_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
