# Generated by Django 6.1 on 2026-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0008_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEBIDO", "Recebido"),
                    ("EM_PREPARO", "Em preparo"),
                    ("PRONTO", "Pronto"),
                    ("ENTREGUE", "Entregue"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="RECEBIDO",
                max_length=20,
            ),
        ),
    ]
