# Generated by Django 6.1 on 2026-08-23 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0011_cliente_usuario"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="produto",
            name="preco_nao_negativo",
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gte", 1)), name="quantidade_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.CheckConstraint(
                condition=models.Q(("preco__gt", 0)), name="preco_positivo"
            ),
        ),
    ]
